### ISSUE TITLE
Težave pri funkciji source

### ISSUE THREAD

**Issue by Nina2809** [Nina2809/APPR-2020-21#1]
Pozdravljeni!

Med izdelavo projekta, sem naletela na težavo pri uporabi `source`. Pri uporabi slednje funkcije mi namreč R zmrzne in se datoteka `moj_uvoz` ne prevede. Zdi se mi, da je težava v tej vrstici: `source("lib/libraries.r", encoding="Windows-1250")`, vendar ne razumem zakaj. Preden sem dodala omenjeno vrstico mi je vse delovalo normalno, sedaj pa program zmrzne. 

Hvala za vašo pomoč!

**Comment by Nina2809** [comment]
Pri nadaljevnju projekta sem opazila, da morda ni težava v funkciji `source`, ampak v nalaganju nekaterih knjiznic, kot je `tmap`. Še vedno pa ne razumem, kako odpraviti to težavo.

**Comment by timotejvesel** [comment]
Kakšno napako ti izpiše, če poženeš ukaz `library(tmap)`?

**Comment by Nina2809** [comment]
Ne izpiše mi nobene napake. R samo zamrzne, tudi če pritisnem `Stop` se ne ustavi in niti ne morem zapreti programa. V tem primeru je vedno edina rešitev, da resetiram računalnik. 

![image](https://user-images.githubusercontent.com/49915013/127767119-df0bb4d6-83ed-41db-93ea-3b51804f8fd6.png)

**Comment by timotejvesel** [comment]
Nevem, mogoče kakšna napaka pri namestitvi paketa. Mogoče bo imel @jaanos kakšno idejo.

**Comment by jaanos** [comment]
Kot pravi @timotejvesel, je najverjetneje težava z namestitvijo paketa `tmap`. Svetujem, da ga poskusiš ponovno namestiti:
```R
install.packages("tmap")
```
Če tudi to ne bo pomagalo, lahko za izrisovanje zemljevidov namesto knjižnice `tmap` uporabiš knjižnico `ggplot2` (poglej si [primer](https://github.com/jaanos/APPR-2018-19/blob/master/vizualizacija/vizualizacija.r) iz predlanskega vzorca).

Ali imaš težave pri nalaganju še katere druge knižnice poleg `tmap`?

**Comment by jaanos** [comment]
Mimogrede, pri `source` uporabi kodiranje znakov `UTF-8`. Pravzaprav bo najbolje, če ta ukaz uporabljaš samo iz poročila - najprej torej naložiš knjižnice z `libraries.r` (pri uvozu in vizualizaciji jih tako ni potrebno še enkrat nalagati), potem pa namesto vzorčnih programov kličeš `mojuvoz.r` in `mojavizualizacija.r`.

**Comment by Nina2809** [comment]
Pozdravljeni!

Sedaj sem dodala

> install.packages("tmap", lib = "C:\\Program Files\\R\\R-3.6.3\\library")
install.packages('Rcpp')
library(Rcpp)

in mi deluje knjižnica `tmap`, z ostalimi knjižnicami zaenkrat še nisem imela težav. 

Najlepša hvala za pomoč!

**Comment by jaanos** [comment]
V redu - ukaze  `install.packages` seveda zakomentiraj, da se knjižnice ne bodo vsakič znova nameščale.
