### ISSUE TITLE
Zemljevid Slovenije po regijah

### ISSUE THREAD

**Issue by Nina2809** [Nina2809/APPR-2020-21#2]
Pozdravljeni!

Rada bi predstavila podatke o številu porok v posamezni regiji na zemljevidu Slovenije. Vendar povezava do zemljevidov ne deluje.

![image](https://user-images.githubusercontent.com/49915013/127870104-0bcb5c51-76ca-416f-a1b8-b1d84735f219.png)

Pogledala sem si tudi primer iz predlanskega vzorca, ki ste mi ga predlagali pri težavi s funkcijo `source`, vendar žal omenjenega primera ne znam spremeniti v zemljevid regij.

Že v naprej hvala za vašo pomoč!

**Comment by jaanos** [comment]
Strežnik, na katerem se nahajajo zemljevidi, je očitno trenutno nedosegljiv - upam, da ga kmalu spet postavijo. Da ti pa ne bo potrebno čakati, sem zemljevid naložil na http://baza.fmf.uni-lj.si/SVN_adm_shp.zip, tako da lahko uporabiš ta naslov.

**Comment by Nina2809** [comment]
Najlepša hvala, sem uporabila vaš naslov in zemljevid deluje.
